[package]
name = "skena"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.88"
clap = { version = "4.5.41", features = ["derive"] }
regex = "1.11.1"
tokio = {version = "1.46.1", features = ["full"]}
toml = "0.9.2"
